"""
WAF Detection Engine

Detects Web Application Firewalls (WAF) and security appliances through:
- Header analysis
- Response pattern matching
- Behavioral fingerprinting
- Known WAF signatures
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional
import re


@dataclass
class WAFDetection:
    """WAF detection result"""
    detected: bool
    waf_name: Optional[str] = None
    confidence: float = 0.0
    indicators: List[str] = field(default_factory=list)
    headers: Dict[str, str] = field(default_factory=dict)
    

class WAFDetector:
    """
    Detects presence of Web Application Firewalls and security appliances.
    
    Detection methods:
    1. Header-based signatures
    2. Cookie patterns
    3. Response body patterns
    4. Behavioral fingerprinting
    """
    
    # WAF header signatures
    WAF_HEADERS = {
        'cloudflare': [
            ('CF-RAY', r'.*'),
            ('CF-Cache-Status', r'.*'),
            ('__cfduid', r'.*'),
            ('Server', r'cloudflare'),
        ],
        'akamai': [
            ('X-Akamai-Transformed', r'.*'),
            ('Server', r'AkamaiGHost'),
        ],
        'imperva': [
            ('X-Iinfo', r'.*'),
            ('X-CDN', r'Incapsula'),
        ],
        'aws_waf': [
            ('X-Amzn-Trace-Id', r'.*'),
            ('X-Amz-Cf-Id', r'.*'),
        ],
        'sucuri': [
            ('X-Sucuri-ID', r'.*'),
            ('X-Sucuri-Cache', r'.*'),
            ('Server', r'Sucuri'),
        ],
        'cloudfront': [
            ('X-Amz-Cf-Id', r'.*'),
            ('X-Amz-Cf-Pop', r'.*'),
            ('Via', r'cloudfront'),
        ],
        'f5_bigip': [
            ('X-WA-Info', r'.*'),
            ('BigipServer', r'.*'),
        ],
        'fortiweb': [
            ('FORTIWAFSID', r'.*'),
        ],
        'barracuda': [
            ('barra_counter_session', r'.*'),
            ('Server', r'Barracuda'),
        ],
        'modsecurity': [
            ('Server', r'.*Mod_Security.*'),
        ],
        'wordfence': [
            ('X-Wordfence-Cache', r'.*'),
        ],
        'webknight': [
            ('Server', r'WebKnight'),
        ],
        'safe3': [
            ('X-Powered-By-360WZB', r'.*'),
        ],
        'naxsi': [
            ('Server', r'.*naxsi.*'),
        ],
    }
    
    # WAF cookie patterns
    WAF_COOKIES = {
        'cloudflare': ['__cfduid', '__cflb', 'cf_clearance'],
        'imperva': ['incap_ses_', 'visid_incap_'],
        'f5_bigip': ['BIGipServer', 'F5_fullWT', 'F5_ST'],
        'fortiweb': ['FORTIWAFSID'],
        'barracuda': ['barra_counter_session'],
        'citrix': ['NSC_', 'citrix_ns_id'],
    }
    
    # WAF response body signatures
    WAF_BODY_PATTERNS = {
        'cloudflare': [
            r'<title>Attention Required! \| Cloudflare</title>',
            r'Please complete the security check to access',
            r'ray id',
        ],
        'imperva': [
            r'Request unsuccessful. Incapsula incident ID',
            r'/_Incapsula_Resource',
        ],
        'sucuri': [
            r'Access Denied - Sucuri Website Firewall',
            r'Questions\? cloudproxy@sucuri\.net',
        ],
        'fortiweb': [
            r'Your request has been blocked by FortiWeb',
            r'For information regarding this error',
        ],
        'wordfence': [
            r'Your access to this site has been limited',
            r'Wordfence',
        ],
        'aws_waf': [
            r'The request could not be satisfied',
            r'Generated by cloudfront',
        ],
        'barracuda': [
            r'You have been blocked by the Barracuda Web Application Firewall',
        ],
        'modsecurity': [
            r'ModSecurity: Access denied',
            r'mod_security',
        ],
    }
    
    def __init__(self):
        """Initialize WAF detector"""
        pass
    
    def detect(self, headers: Dict[str, str], cookies: Dict[str, str], 
               body: Optional[str] = None, status_code: int = 200) -> WAFDetection:
        """
        Detect WAF from HTTP response data.
        
        Args:
            headers: Response headers
            cookies: Response cookies
            body: Response body (optional)
            status_code: HTTP status code
            
        Returns:
            WAFDetection with results
        """
        results = []
        
        # Header-based detection
        header_detections = self._detect_from_headers(headers)
        results.extend(header_detections)
        
        # Cookie-based detection
        cookie_detections = self._detect_from_cookies(cookies)
        results.extend(cookie_detections)
        
        # Body-based detection
        if body:
            body_detections = self._detect_from_body(body)
            results.extend(body_detections)
        
        # Aggregate results
        if results:
            # Get most confident detection
            best_detection = max(results, key=lambda x: x['confidence'])
            
            return WAFDetection(
                detected=True,
                waf_name=best_detection['waf'],
                confidence=best_detection['confidence'],
                indicators=best_detection['indicators'],
                headers={k: v for k, v in headers.items() if k in best_detection.get('matched_headers', [])}
            )
        
        return WAFDetection(detected=False)
    
    def _detect_from_headers(self, headers: Dict[str, str]) -> List[Dict]:
        """Detect WAF from HTTP headers"""
        detections = []
        
        # Normalize header names (case-insensitive)
        normalized_headers = {k.lower(): v for k, v in headers.items()}
        
        for waf_name, signatures in self.WAF_HEADERS.items():
            matched = []
            for header_name, pattern in signatures:
                header_key = header_name.lower()
                if header_key in normalized_headers:
                    value = normalized_headers[header_key]
                    if re.search(pattern, value, re.IGNORECASE):
                        matched.append(f"Header: {header_name}={value}")
            
            if matched:
                detections.append({
                    'waf': waf_name,
                    'confidence': min(1.0, len(matched) * 0.4),
                    'indicators': matched,
                    'matched_headers': [sig[0] for sig in signatures if sig[0].lower() in normalized_headers]
                })
        
        return detections
    
    def _detect_from_cookies(self, cookies: Dict[str, str]) -> List[Dict]:
        """Detect WAF from cookies"""
        detections = []
        
        for waf_name, cookie_patterns in self.WAF_COOKIES.items():
            matched = []
            for cookie_name in cookies.keys():
                for pattern in cookie_patterns:
                    if pattern in cookie_name or cookie_name.startswith(pattern):
                        matched.append(f"Cookie: {cookie_name}")
            
            if matched:
                detections.append({
                    'waf': waf_name,
                    'confidence': min(1.0, len(matched) * 0.5),
                    'indicators': matched,
                    'matched_headers': []
                })
        
        return detections
    
    def _detect_from_body(self, body: str) -> List[Dict]:
        """Detect WAF from response body"""
        detections = []
        
        for waf_name, patterns in self.WAF_BODY_PATTERNS.items():
            matched = []
            for pattern in patterns:
                if re.search(pattern, body, re.IGNORECASE):
                    matched.append(f"Body pattern: {pattern[:50]}...")
            
            if matched:
                detections.append({
                    'waf': waf_name,
                    'confidence': min(1.0, len(matched) * 0.6),
                    'indicators': matched,
                    'matched_headers': []
                })
        
        return detections
    
    def get_detection_advice(self, waf_name: str) -> Dict[str, str]:
        """
        Get scanning advice based on detected WAF.
        
        Args:
            waf_name: Name of detected WAF
            
        Returns:
            Dictionary with scanning advice
        """
        advice = {
            'cloudflare': {
                'rate_limiting': 'Aggressive rate limiting - reduce scan speed',
                'behavior': 'Blocks suspicious patterns - use minimal payloads',
                'recommendation': 'Use legitimate user-agent, reduce parallelism'
            },
            'imperva': {
                'rate_limiting': 'Sophisticated behavioral analysis',
                'behavior': 'Detects automated tools - randomize timing',
                'recommendation': 'Human-like request patterns, avoid bulk testing'
            },
            'aws_waf': {
                'rate_limiting': 'Configurable rules - varies by implementation',
                'behavior': 'Can block by IP, pattern, or geo-location',
                'recommendation': 'Test rate limits, use minimal signatures'
            },
            'modsecurity': {
                'rate_limiting': 'Rule-based blocking',
                'behavior': 'OWASP CRS may block common payloads',
                'recommendation': 'Use evasion techniques, test bypass methods'
            },
        }
        
        return advice.get(waf_name, {
            'rate_limiting': 'Unknown WAF behavior',
            'behavior': 'Proceed with caution',
            'recommendation': 'Reduce scan aggressiveness, monitor for blocks'
        })
